apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-primaza
spec:
  params:
    - default: 'user1-tenant'
      name: NAMESPACE
      description: Namespace of the application under test
  results:
    - name: TEST_OUTPUT
      description: Test output
  steps:
    - image: bitnami/kubectl
      env:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
      script: |
        #!/usr/bin/env bash
        EXPECTED_OUTPUT="SomeoneThinksImAPassword"
        export KUBECONFIG=$(workspaces.cluster-credentials.path)/kubeconfig

        # Get the environment binding for teh application
        ACTUAL_OUTPUT=$(kubectl exec $(kubectl get pod -l app=my-go -o jsonpath='{.items[0].metadata.name}' -n "${NAMESPACE}") -n "${NAMESPACE}" -- cat /bindings/my-app-dummy-for-appns/password)

        if [[ "${ACTUAL_OUTPUT}" == "${EXPECTED_OUTPUT}" ]]; then
          RESULT="SUCCESS"
        else
          RESULT="FAILURE"
        fi

        TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --arg ACTUAL_OUTPUT "${ACTUAL_OUTPUT}" --arg EXPECTED_OUTPUT "${EXPECTED_OUTPUT}"  --null-input \
          '{result: $RESULT, timestamp: $date, actual_output:$ACTUAL_OUTPUT, expected_output: EXPECTED_OUTPUT, failures: 0, successes: 0, warnings: 0}')
        echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
  workspaces:
    - name: cluster-credentials
      optional: true