apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integration-primaza-pass
spec:
  description: >-
    Expects a Snapshot of a simple application with endpoint containing the expected output to be deployed on an environment.
    A secret containing the kubeconfig for the environment needs to be mounted via the cluster-credentials workspace binding.
    The route to the single component is expected to have the same name as the component (default appstudio behavior).
  params:
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "user1-tenant"
      type: string
    - description: 'Service Binding in application namespace'
      name: BINDING
      default: "my-app-dummy-for-appns"
      type: string
    - description: 'Bound variable key'
      name: KEY
      default: "password"
      type: string
  tasks:
    - name: test-primaza
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/appsvc-rhtap/integration-examples
          - name: revision
            value: primaza-integration-test
          - name: pathInRepo
            value: tasks/test_primaza.yaml
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
      workspaces:
        - name: cluster-credentials
          workspace: cluster-credentials
  workspaces:
    - name: cluster-credentials
      optional: true